### ISSUE TITLE
RegisterPersistenceThread没有合理的使用offset文件和offset.bak文件

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#1]
offset.bak文件没有发挥备份作用。在offset或offset.bak写入失败后，没有做相应处理

**Comment by tanzhen84** [comment]
haha

**Comment by ascrutae** [comment]
已经解决

**Comment by wu-sheng** [comment]
offset与offset.bak依然在文件写入错误的情况下，可能造成offset文件读写不正确。

**Comment by wu-sheng** [comment]
2.0版本将不再存在此文件。将移除此内容，直接进行本地入库处理。使用新的分布式模式。
