### ISSUE TITLE
Change the akka's mailbox queue to disruptor

### ISSUE THREAD

**Issue by pengys5** [wu-sheng/sky-walking#100]
We used akka's mailbox, but akka's mailbox implementation of java.util.concurrent.ConcurrentLinkedQueue. The performance is not good, so we will change it to disruptor.

**Comment by wu-sheng** [comment]
After I and @pengys5 discuss, the akka mailbox is in push mode, but in the other hand, disruptor is in pull mode. It is very hard to match these two.

But we all concern about jdk-queue, so decide use a new queue based on `AtomicInteger`, at least, have better performance.

**Comment by wu-sheng** [comment]
@pengys5 I have removed the milestone, since this issue isn't urgent.

**Comment by wu-sheng** [comment]
Since we have removed akka in 3.2, I am going to close this issue.
