### ISSUE TITLE
Support transaction sampling

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#110]
If agent send all TraceSegment to collector-cluster, it costs so much network bandwidth.

We provide a config set the percentage of sampling. This minimum unit is 1/10000, which means send one TraceSegment to the collector every 10000 times.

When we face this scenario: A -> B, if TraceSegment is sampled in A, then the related TraceSegment in B must be sampled, no matter you sampling rate.

If we want to support this, we will add a new field(`sampling`) in TraceSegmentRef.

cc @ascrutae.

And @pengys5 , I think this do not influence the Collector? Confirm?

**Comment by wu-sheng** [comment]
Tested already. Provide `agent.sampling_cycle` in `sky-walking.config` file. 

If `agent.sampling_cycle=n`, meaning, select one trace in every `n` traces.

**Comment by wu-sheng** [comment]
`agent.sampling_cycle`, default is **1**, means, sampling **OFF**.

**Comment by psc0606** [comment]
Unitl now, skywalking seems still not support transaction sampling.
