### ISSUE TITLE
[Integration test] Test agent and collector cluster

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#112]
Run test on [branch 3.0](https://github.com/wu-sheng/sky-walking/tree/feature/3.0)

List all issues here.

**Comment by ascrutae** [comment]
# Test Application
**Portal Server**:  Running in tomcat container.
**Cache Server**:   Server  side of motan,  there are two services running in cache server 
**Persistence Server**:  Server side of dubbo. 
**Skywalking collector**:  skywalking collector is Collect trace data. There are 3 instance of skywalking collector. 

The call graph is as follows:
![1](https://cloud.githubusercontent.com/assets/12436447/24838594/81f793ec-1d7d-11e7-9c5d-a7d64aaa4fcf.png)

Here are the configuration file of each application:
- Portal Server:
	Portal server pass the config parameteres through system properties.  
```
-javaagent:/skywalking-test/agent/skywalking-agent.jar -DapplicationCode=portal-service -Dservers=127.0.0.1:7001,127.0.0.1:17001,127.0.0.1:27001
```

- Cache Server:
Cache server pass the config parameteres through `sky-walking.config` file
```
-javaagent:/skywalking-test/agent/skywalking-agent.jar -DconfigPath=/path/of/sky-walking.config
```

Here is the context of sky-walking.config

```properties
agent.application_code=cache-service
collector.servers=127.0.0.1:7001,127.0.0.1:17001,127.0.0.1:27001
```
- Persistence Server:
Same as Portal server.
```
-javaagent:/skywalking-test/agent/skywalking-agent.jar -DapplicationCode=persistence-service -Dservers=127.0.0.1:7001,127.0.0.1:17001,127.0.0.1:27001
```
-  Skywalking collector:
Here are the `collector.config` of three collector instances.
**Instance One**:
```
cluster.current.hostname=127.0.0.1
cluster.current.port=7000
cluster.seed_nodes=127.0.0.1:7000,127.0.0.1:17000,,127.0.0.1:27000
http.hostname=127.0.0.1
http.port=7001
```

**Instance Two**:
```
cluster.current.hostname=127.0.0.1
cluster.current.port=17000
cluster.seed_nodes=127.0.0.1:7000,127.0.0.1:17000,,127.0.0.1:27000
http.hostname=127.0.0.1
http.port=17001
```

**Instance Three**:
```
cluster.current.hostname=127.0.0.1
cluster.current.port=27000
cluster.seed_nodes=127.0.0.1:7000,127.0.0.1:17000,,127.0.0.1:27000
http.hostname=127.0.0.1
http.port=27001
```

#  topological graph
<img width="1438" alt="topological_graph" src="https://cloud.githubusercontent.com/assets/12436447/24838609/a96f9dca-1d7d-11e7-97c7-e9dc956c436d.png">
