### ISSUE TITLE
[Collector]Open ip:port config of Elastic search client, also support cluster mode

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#115]
In `EsClient`, current codes are like this:
```java
client = new PreBuiltTransportClient(settings)
                .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300));
```

Should:
1. `ip:port` comes from config file.
1. Support multi transport addresses.

**Comment by pengys5** [comment]
Set the elasticsearch cluster node config in collector.config file.

- cluster model: 
es.cluster.nodes=127.0.0.1:9300,127.0.0.2:9300,127.0.0.3:9300
- standalone
model: es.cluster.nodes=127.0.0.1:9300
