### ISSUE TITLE
[Collector]Open cluster.name config of Elastic search client

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#116]
In `EsClient`, "cluster.name" is setting to "CollectorCluster", as a constant.  Should provide it in config file. And `CollectorCluster` is an unreasonable name, it is the name of a elastic search cluster, nothing about **collector**.

**Comment by pengys5** [comment]
Set the elasticsearch cluster config in collector.config file.
es.cluster.name
es.cluster.nodes
es.cluster.transport.sniffer
And the index setting also in collector.config file.
es.index.shards.number
es.index.replicas.number
