### ISSUE TITLE
[Collector] Add comments for "collector.config"

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#126]
There are so many config items in `collector.config`, but no comments. 

@pengys5 You have two opinions:
1. Add a document in wiki pages, like agent did: https://github.com/wu-sheng/sky-walking/wiki/sky-walking-config-file-walkthrough
1. Add comments in the `collector.config` file, like this:

```properties
# Application code is showed in sky-walking-ui.
# Suggestion: set a unique name for each application, one application's nodes share the same code.
agent.application_code=Your_ApplicationName
```

**Comment by pengys5** [comment]
fix
