### ISSUE TITLE
授权文件的配置可以根据不同的选项可以支持各种网络环境

### ISSUE THREAD

**Issue by ascrutae** [wu-sheng/sky-walking#13]
目前生成的授权文件中的日志手机的服务器只能生成内网地址，不支持生成各种网络环境的地址生成，需要支持的网络环境有：内网，外网。

**Comment by wu-sheng** [comment]
使用授权文件的不同文件区分内外网，不要使用专有字段，避免提高程序复杂度。

**Comment by ascrutae** [comment]
已修复，在页面中可以选择是否为内外网的类型
