### ISSUE TITLE
Add wiki pages about how to use collector.tar and collector image.

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#131]
Get ready, we are going to release at Friday.

**Comment by wu-sheng** [comment]
@ascrutae Are you done?

I found two wiki pages about this: https://github.com/wu-sheng/sky-walking/wiki/3.0-Deploy-docker-image and https://github.com/wu-sheng/sky-walking/wiki/3.0-部署Collector镜像

**Comment by ascrutae** [comment]
The wiki pages has been done! Close this issue
