### ISSUE TITLE
ERROR: repository skywalking-collector not found: does not exist or no pull acces

### ISSUE THREAD

**Issue by bill23-kim** [wu-sheng/sky-walking#134]
There seems to be no skywalking-collector, sky-walking-ui image yet on the docker hub. Do you 
plan to upload soon?

**Comment by wu-sheng** [comment]
Are you looking for the 3.0 docker image? If so, please wait for two more days. After we release 3.0 officially, you will get the images.

**Comment by bill23-kim** [comment]
thank you
