### ISSUE TITLE
In Agent-API module, Httpclient has potential performance issue.

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#138]
- Management of http connection seems not good enough.

@pengys5 Can you give me some demonstration for http connection test?

**Comment by pengys5** [comment]
Change  apache http client to okhttp client.
Sample code:
> public final MediaType JSON = MediaType.parse("application/json; charset=utf-8");
> private OkHttpClient client = new OkHttpClient();

> public String post(String url, String data) throws IOException {
> 　RequestBody body = RequestBody.create(JSON, data);
> 　Request request = new Request.Builder().url(url).post(body).build();
> 　Response response = client.newCall(request).execute();
> 　return response.body().string();
> }

**Comment by wu-sheng** [comment]
okhttp 3.6.0 based on jdk7.... cant NOT use it in agent.

**Comment by wu-sheng** [comment]
Options:
1. okhttp 1.6
1. jetty

**Comment by pengys5** [comment]
okhttp 1.6 sample, performance metric same as 3.6 version
> public final MediaType JSON = MediaType.parse("application/json; charset=utf-8");
> private OkHttpClient client = new OkHttpClient();
>
> public String post(String url, String data) throws IOException {
> 　HttpURLConnection connection = client.open(new URL(url));
> 　OutputStream out = null;
> 　InputStream in = null;
> 　try {
> 　　// Write the request.
> 　　connection.setRequestMethod("POST");
> 　　out = connection.getOutputStream();
> 　　out.write(data.getBytes());
> 　　out.close();

> 　　 // Read the response.
> 　　 if (connection.getResponseCode() != HttpURLConnection.HTTP_OK) {
> 　　　　throw new IOException("Unexpected HTTP response: " + connection.getResponseCode() + " " > 　　　　+ connection.getResponseMessage());
> 　　}
> 　　in = connection.getInputStream();
> 　　return readFirstLine(in);
> 　} finally {
> 　　 // Clean up.
> 　　if (out != null) out.close();
> 　　if (in != null) in.close();
>　}
>}

> String readFirstLine(InputStream in) throws IOException {
> 　　BufferedReader reader = new BufferedReader(new InputStreamReader(in, "UTF-8"));
>　　return reader.readLine();
>}

**Comment by wu-sheng** [comment]
@pengys5 Please post codes like this:
```java
 public final MediaType JSON = MediaType.parse("application/json; charset=utf-8");
 private OkHttpClient client = new OkHttpClient();

 public String post(String url, String data) throws IOException {
 　HttpURLConnection connection = client.open(new URL(url));
 　OutputStream out = null;
 　InputStream in = null;
     try {
 　　// Write the request.
 　　connection.setRequestMethod("POST");
 　　out = connection.getOutputStream();
 　　out.write(data.getBytes());
 　　out.close();

 　　 // Read the response.
 　　 if (connection.getResponseCode() != HttpURLConnection.HTTP_OK) {
 　　　　throw new IOException("Unexpected HTTP response: " + connection.getResponseCode() + " "  　　　　+ connection.getResponseMessage());
 　　}
 　　in = connection.getInputStream();
 　　return readFirstLine(in);
 　} finally {
 　　 // Clean up.
 　　if (out != null) out.close();
 　　if (in != null) in.close();
　}
}

 String readFirstLine(InputStream in) throws IOException {
 　　BufferedReader reader = new BufferedReader(new InputStreamReader(in, "UTF-8"));
　　return reader.readLine();
}
```

**Comment by wu-sheng** [comment]
Need more test to decide what should we do.

**Comment by wu-sheng** [comment]
In 3.3, we have decided to use GRPC for improving performance. Check here: https://github.com/wu-sheng/sky-walking/issues/236#issuecomment-310268231
