### ISSUE TITLE
Official website: skywalking.org

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#146]
**www.skywalking.org**

**Comment by pengys5** [comment]
fixed

**Comment by wu-sheng** [comment]
@pengys5  The website is **NOT** ready yet.

**Comment by wu-sheng** [comment]
cc @TastySummer, when you are ready, please let me know.

**Comment by wu-sheng** [comment]
Almost finished, just need fix some typo.

**Comment by wu-sheng** [comment]
@TastySummer, Thanks for your contributions.
