### ISSUE TITLE
Support plugin for MongoDB

### ISSUE THREAD

**Issue by bai-yang** [wu-sheng/sky-walking#147]
Hi all：
MongoDB is a database based on distributed file storage. Designed to provide scalable high-performance data storage solutions for WEB applications. So I Developed MongoDB Plugin For SkyWalking.

MongoDB Plugin Contribution
Link: /skywalking/skywalking-sniffer/skywalking-sdk-plugin/skywalking-mongodb-plugin
Supported Version: mongo-java-driver-3.X.X
I have tested based on version  mongo-java-driver-3.4.2，it can work.

![mongo1](https://cloud.githubusercontent.com/assets/20091216/25089309/366b712c-23af-11e7-8044-dffa6a1b3bcd.jpeg)
![mongo2](https://cloud.githubusercontent.com/assets/20091216/25089373/9e509484-23af-11e7-9336-72455fc0ca75.jpeg)
![find](https://cloud.githubusercontent.com/assets/20091216/25139810/f44faf00-2490-11e7-8874-e15aef5cb2ff.jpeg)
![insert](https://cloud.githubusercontent.com/assets/20091216/25139828/fa07093e-2490-11e7-9503-f184be3866b9.jpeg)

**Comment by wu-sheng** [comment]
Also related to https://github.com/wu-sheng/sky-walking-ui/pull/10

**Comment by wu-sheng** [comment]
First, thank you for you contribution. `MongoDB` is a necessary plugin, which we have not provided yet. 

I have give your some suggestions before merging. Check #148 . Hope we can have this feature soon.

**Comment by wu-sheng** [comment]
This feature has already merged. @bai-yang Thanks again.
