### ISSUE TITLE
what‘s architecture design of the sky-walking framework ?

### ISSUE THREAD

**Issue by wangzhenxyz1** [wu-sheng/sky-walking#153]

**Comment by wu-sheng** [comment]
Add a new document. @pengys5

**Comment by pengys5** [comment]
<img src="https://sky-walking.github.io/page-resources/3.0/skywalking.png" alt="Sky Walking logo" height="90px" align="right" />

**Comment by pengys5** [comment]
cc @wangzhenxyz1,  this is data process flow graph, close the issues if no more question or I will close it after 48 hours.

**Comment by wu-sheng** [comment]
Please give the readers more details about how `select` works? e.g. In-process, across-process select.

**Comment by wangzhenxyz1** [comment]
thx
