### ISSUE TITLE
Add RPC support for spring-cloud-netflix

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#160]
For now, I have not set the **Milestone**. Reply me, if you are certain what you are going to do. @ascrutae

**Comment by wu-sheng** [comment]
- In spring-cloud ecosystem, by default, the server-side use embed Tomcat (uncertain the version, yet), so maybe we already supported.

- In client side, here is some answers from Adrian Cole, Spring
https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/client/support/HttpAccessor.html#setRequestFactory-org.springframework.http.client.ClientHttpRequestFactory-
so default for resttemplate (the normal rest library) is standard library (HttpUrlConnection), but it can use others like okhttp.

**Comment by wu-sheng** [comment]
By doing this, please set a demo about spring-resttemplete. In theory, they should use the same i/o component.

**Comment by wu-sheng** [comment]
```
Spring Cloud Netflix  ->  REST Client: Feign  ->  ApacheHttpClient/ribbon(maybe)/okhttp
```

cc @pengys5

**Comment by pengys5** [comment]
Feign is a java to http client binder inspired by Retrofit, JAXRS-2.0, and WebSocket.
Spring Cloud integrates Ribbon and Eureka to provide a load balanced http client when using Feign.
Feign provide JAX-RS,OkHttp,httpclient,HttpURLConnection.

So if we provide JAX-RS,OkHttp,httpclient,HttpURLConnection plugins, skywalking will support spring cloud restful interface.

**Comment by wu-sheng** [comment]
@pengys5 I think we should close this, right? We can support spring cloud config center in next version. Agree?
