### ISSUE TITLE
Integration Test before 3.0.1 release

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#166]

**Comment by ascrutae** [comment]
Here are the snapscreens.

* topology graph
<img width="1436" alt="wx20170427-153630 2x" src="https://cloud.githubusercontent.com/assets/12436447/25478128/7ec82710-2b72-11e7-82a1-52797c608842.png">

* trace graph
![snip20170427_4](https://cloud.githubusercontent.com/assets/12436447/25478309/3675982a-2b73-11e7-823f-b5cfcc839a5c.png)


* span graph
<img width="1044" alt="wx20170427-175652 2x" src="https://cloud.githubusercontent.com/assets/12436447/25478234/ebdb02fa-2b72-11e7-8ed1-5ce6352cc03e.png">
