### ISSUE TITLE
Potential bug for OpenTracing activation, when format is "Format.Builtin.BINARY"

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#167]
From code review, it is a potential bug. `Format.Builtin.TEXT_MAP` seems fine.

@ascrutae please recheck the codes, before we release 3.0.1, tomorrow.

**Comment by wu-sheng** [comment]
@ascrutae At the same time, please refactor the `SkyWalkingTracer.inject` and `SkyWalkingTracer.extract` , when the format is `Format.Builtin.TEXT_MAP`.

Keep the activation as simple as possible.

**Comment by ascrutae** [comment]
The context by using `Format.Builtin.BINARY_MAP` can not propagation across process,because the format extract data process are not consistent with the format of the extract data. I change the logic of format extract data and tested.
