### ISSUE TITLE
Add deploy with docker in doc

### ISSUE THREAD

**Issue by hacpai** [wu-sheng/sky-walking#170]

**Comment by wu-sheng** [comment]
We will provide docker image recently. We already have pr(https://github.com/wu-sheng/sky-walking/pull/163) and issue(https://github.com/wu-sheng/sky-walking/issues/162). When we finish those two, we will provide documents.

**Comment by ascrutae** [comment]
Here are the documents about deploy image .
EN:[Deploy collector image](https://github.com/wu-sheng/sky-walking/wiki/3.0-Deploy-docker-image)
ZH:[部署Collector镜像](https://github.com/wu-sheng/sky-walking/wiki/3.0-部署Collector镜像)
