### ISSUE TITLE
Should add the .gitignore file to the project

### ISSUE THREAD

**Issue by xcaspar** [wu-sheng/sky-walking#174]
The project is missing `.gitignore` file which specifies intentionally untracked files that Git should ignore. When I clone the code, the Git prompts that the `.iml` files are not being tracked, these files should be ignored.

**Comment by wu-sheng** [comment]
Agree, welcome you to send a pull request to fix this.

**Comment by xcaspar** [comment]
I have submitted a PR #175 , please view it.
