### ISSUE TITLE
Start collector or webui, return success, but fail

### ISSUE THREAD

**Issue by xcaspar** [wu-sheng/sky-walking#180]
When I use JDK7 to start the component(collector or webui), the console displays the message:
`Starting collector....
Collector started successfully!`
But because of the JDK version is earlier than JDK8, the startup failed, the process does not exist.

Can add a check for java version or process id to avoid the problem.

**Comment by wu-sheng** [comment]
Agree.  cc @ascrutae @pengys5

**Comment by wu-sheng** [comment]
@xcaspar We just rename all the package, as we have the `skywalking.org` website in recent future. If you want to contribute any things about java codes, your better choice is to sync with `wu-sheng/sky-walking` first.

**Comment by xcaspar** [comment]
@wu-sheng Good! OK.  To this issue, I will submit a PR later.

**Comment by wu-sheng** [comment]
@xcaspar Do you have any update? Or Do you intend to do so?

**Comment by xcaspar** [comment]
@wu-sheng Sorry to reply so late. I have nothing to update.

**Comment by wu-sheng** [comment]
@xcaspar Your pr has been merged. By your contribution, you can send a pr to add yourseft in the contributors list, in `README` file, if you want.

If you do so, please ping me on your pr.
