### ISSUE TITLE
Rename the "apm-api" module to "apm-agent-core"

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#181]
"API" is not the exact word for this very important module. "API" means interfaces at most time, but in this module, include almost all core(important) codes at agent-side.

So, I have to rename this module once for all.

And, another tiny adjustment is for module `apm-commons/apm-util`, the source codes in that is sharing the package name with `api` module. I will change the package name to `org.skywalking.apm.util`

cc @pengys5 @ascrutae @bai-yang @xcaspar I assume your guys should notice this. I will create a pr soon.

**Comment by wu-sheng** [comment]
And @ascrutae , I think you should run an integration test for that pr.

**Comment by ascrutae** [comment]
Got it

**Comment by wu-sheng** [comment]
@ascrutae #182 has been merged, please run tests on `master`.

**Comment by wu-sheng** [comment]
Based on https://github.com/wu-sheng/sky-walking/pull/182#issuecomment-298318389, closing.
