### ISSUE TITLE
Instance discovery

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#183]
Now, from UI, we can just tell the applicationCode,but don't include instances information. We should improve that.

Here is my proposal:
1. Generate a instance id(UUID) when agent starts. 
1. Send to collector, and get an integer id(instance-id) instead. At collector-side, provide a instance sequence for distributed application instances.(Need more discussion)
1. Agent send trace segments with this instance-id.
1. By using this id, collector can tell how many instances for each application code.

cc @sky-walking, wait for your response on this.

**Comment by pengys5** [comment]
1. The UUID what will happen when agent restarted. 
      (1) Use the preceding UUID. But that may pose a problem, how to discern the agent which is not changed? Use the information of server, like IP address, MAC Address,etc., but, if the agent running in container platform, when agent restarted, the server changed too.
      (2) Generate a new one. we want a timeout mechanism, insure that the stoped agent unable to show in UI.
  1. The UUID contains application code(A-UUID).
  1. The application code in trace segments instead of this integer id(instance-id).

cc @sky-walking

**Comment by wu-sheng** [comment]
> The UUID what will happen when agent restarted.

@pengys5 `Happen` means `change`, I presume. You **CAN NOT** make sure the **ID** won't change at all circumstances. So in my proposal, I ask for a instance-id ( an integer ), for applicationCode + instanceId. 

This instance-id can be translated at collector-side, as an applicationCode and a instance-sequence.

But if you think translation at collector-side will cost too much (including memory and sync), we can set `instance-id = instance-sequence`.

The `the amount of instance` is determined by the trace segments, by distinct all instance-id in the time slice. The tricky question is `How you show the instance amount`?

**Comment by pengys5** [comment]
@wu-sheng In my mind, the instance amount is the same as the relation between segment id and global trace id.

**Comment by wu-sheng** [comment]
@pengys5 What is your meaning about **between**? These ids are changing at any moment. Like reboot an application, id_a disappear without any notice, and id_b begin to report.

**Comment by ascrutae** [comment]
Why don't add heartbeat mechanism to each agent?

**Comment by ascrutae** [comment]
Q1: Why don't we generate instance id by instance environment? just like IP address, host name or service port.  Is send an integer can save more network?

In my mind. we can add instance-id to echo trace segment, and then send it to collector, We can use the start time and end time of each segment to analysis the agent which is up or down.

**Comment by wu-sheng** [comment]
> We can use the start time and end time of each segment to analysis the agent which is up or down

You can know which agents are running, at least how many agents are running. But you definitely can not tell which is stopped. Because no trace segment didn't mean **stopped**, maybe the application is just a hot/backup instance node.

**Comment by wu-sheng** [comment]
> Q: Why don't we generate instance id by instance environment? just like IP address, host name or service port. Is send an integer can save more network?

This is actually two questions.
1. `generate instance id by instance environment`, because in docker, can't guarantee any environment is different from others. 
1. `send an integer can save more network`, I think this is an improvement of performance. This is irrelative with instance-id.

**Comment by pengys5** [comment]
Use restful service.

1. register service: The agent send the application code and jvm information to the collector server when agent start, data construct:
  request: `{"ac":"?","vm":{"?":"?"...}}`
  response: `{"ii":"instance id"}`

1. heartbeat service: The agent send the heartbeat data to the collector server every once in a while(undetermined time). The collector server mark the state of agent to stoped when collector server can not receive heartbeat data exceed the time limit, data construct:
  request: `{"ii":"instance id"}`
  response: `status code 200`

**Comment by pengys5** [comment]
Persistence data construct: 
instance_idx: `"id":"instance id", "ac","application code", "st": "start time", "et": "last heartbeat time", "vm": {"?": "?" ..}`

**Comment by pengys5** [comment]
Agent matching logic in time slice:

**Comment by wu-sheng** [comment]
@pengys5 

> request: {"ac":"?","vm":{"?":"?"...}}
response: {"ii":"instance id"}

From your register service, you want agents to report `ApplicationCode` and `vm`, are you going to generate `instance id` by both `ac` and `vm`? Why do you need the `vm` info?

And if the instance-id includes applicationCode, does traceSegment still include applicationCode? If not, trace-receive-service needs translate instance-id of every traceSegment. By doing that, you need sync all instance-ids in the whole collector-cluster, are you sure about this?

**Comment by wu-sheng** [comment]
Your instance-discovery need base on a superposition algorithm. It is a little hard to find the amount of instances in a time slice.

Besides, your match mechanism seems impossible, because if instance-A running from t1 -> t1 + 10, at t1+12, instance-B and instance-C register both, you are impossible to tell `A = B` or ` A = C`, or neither.

Only choice is, basing on a superposition algorithm, in t1 -> t1 + 20, almost 2 instances are running.

**Comment by wu-sheng** [comment]
cc @pengys5 @ascrutae I had set this as part of 3.1 milestone.

**Comment by ascrutae** [comment]
@sky-walking the MAC address and process no of current jvm can generate unique instance ID so that we don't sync instance ID in whole collector cluster.

**Comment by ascrutae** [comment]
@sky-walking, I think we just record the`live time range` of  instance ( live time rang =  last hear beat time - registry time ).  and we just check the live time range is with in the time range of the query when use search instance number. There are only four scenarios：
scenarios 1:  the registry time **BEFORE** the start time of the query and the last hear beat time **AFTER** the end time of the query,  We can add the instance  number in this scenarios.
scenarios 2: the registry time ** BEFORE** the start time of the query and the last hear beat time **BEFORE** the end time of the query, We cannot add the instance  number in this scenarios.
**scenarios 3**: the registry time **AFTER** the start time of the query and the last hear beat time **AFTER** the end time of the query. We can add the instance  number in this scenarios.
**scenarios 4**: the registry time **AFTER** the start time of the query and the last hear beat time **BEFORE** the end time of the query. We cannot add the instance  number in this scenarios.

**Comment by wu-sheng** [comment]
@ascrutae As deadline comes, I have to change the milestone to 3.2. Hope you can catch up. 💪

**Comment by wu-sheng** [comment]
I provided the zh-document about **Instance Discovery**: [实例发现.docx](https://github.com/wu-sheng/sky-walking/files/1049635/default.docx)

**Comment by wu-sheng** [comment]
Provided instance discovery through new GRPC protocol.

**Comment by kannan84240** [comment]
> Now, from UI, we can just tell the applicationCode,but don't include instances information. We should improve that.
> 
> Here is my proposal:
> 
> 1. Generate a instance id(UUID) when agent starts.
> 2. Send to collector, and get an integer id(instance-id) instead. At collector-side, provide a instance sequence for distributed application instances.(Need more discussion)
> 3. Agent send trace segments with this instance-id.
> 4. By using this id, collector can tell how many instances for each application code.
> 
> cc @sky-walking, wait for your response on this.

How can i generate UUID for instance and also remaining ?

**Comment by wu-sheng** [comment]
@kannan84240 This was 5 years ago discussion. You have no point to reply here.
