### ISSUE TITLE
Support plugin for Resin

### ISSUE THREAD

**Issue by bai-yang** [wu-sheng/sky-walking#184]
Dear all:
Resin is a fast, ultra-reliable Java EE integrated solution for web applications spanning hundreds of servers.

Resin Plugin Contribution
Link: /apm/skywalking-sniffer/apm-sdk-plugin/apm-resin-3.x-4.x-plugin
Supported Version: resin-3.X.X  resin-4.X.X
I have tested based on version resin-3.1.15 and resin-4.0.41，it can work.

![1](https://cloud.githubusercontent.com/assets/20091216/25563494/bcbc083e-2dcf-11e7-9a7c-fe116d088ec1.png)
![2](https://cloud.githubusercontent.com/assets/20091216/25563520/02ecfaf2-2dd0-11e7-9085-12d9cbe74402.png)
![3](https://cloud.githubusercontent.com/assets/20091216/25563514/eda42652-2dcf-11e7-9f77-e184026aa2a8.png)

**Comment by wu-sheng** [comment]
@bai-yang The pr is closed a moment ago. Why?

**Comment by wu-sheng** [comment]
After #196 is merged, this issue will be closed.

**Comment by wu-sheng** [comment]
@bai-yang @ascruta  Closing this issue. Thank you  for your contributions.

**Comment by Ltianci** [comment]
I found the latest version can't support resin-pro 4.0.59 , except update start.sh ,is there any other operation?
