### ISSUE TITLE
Witness class mechanism fails, when its classloader is not the default(BootupClassLoader)

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#189]
`AbstractClassEnhancePluginDefine.classTypePool` is initialized by `TypePool classTypePool = TypePool.Default.ofClassPath();`.

IMO, this has a potential bug, when the witness class can't be loaded by default ClassLoader, witness class resolution will not be resolved.

cc @sky-walking

**Comment by ascrutae** [comment]
This could be a bug. I will test it first.

**Comment by wu-sheng** [comment]
This bug has been confrimed. I will fix this soon.

**Comment by ascrutae** [comment]
It was tested successfully in the case which the witness class and enhance class are loaded by the same classloader.
