### ISSUE TITLE
如何跟spring boot 结合使用？

### ISSUE THREAD

**Issue by ExtremeYu** [wu-sheng/sky-walking#202]

**Comment by wu-sheng** [comment]
首先，我们会支持Spring boot和cloud中的同步调用，我们由于已经支持Tomcat 7+的内核，所以Spring boot的mvc已经被支持，无需其他扩展，即服务提供方已支持。

其次针对客户端，要看你使用哪种rest框架进行调用，目前已经支持的是okhttp 3.x(https://github.com/wu-sheng/sky-walking/pull/197)和httpclient。

目前支持的框架列表可参考
- 开发版本：https://github.com/wu-sheng/sky-walking/tree/master/apm-sniffer/apm-sdk-plugin
- 发布版本：https://github.com/wu-sheng/sky-walking/wiki/3.0-supported-list

@pengys5 将很快提供更多的http客户端框架的支持。

**Comment by ExtremeYu** [comment]
目前是这样的，portal(http)→flow(dubbo rpc)→busi(dubbo rpc)→persistence(dubbo rpc)这种能追踪吗，混合的协议

**Comment by ExtremeYu** [comment]
dubbo本身自带容器可以启动，但是我是用了sprngboot整合了dubbo，用springboot的main方法顺带启动了dubbo，这种监控有没有有什么问题

**Comment by ExtremeYu** [comment]
反正韩国的pinpoint 显示的是一团糟

**Comment by wu-sheng** [comment]
portal是spring boot web么？应该是没有问题。你可以用一个简单测试一下。我们首页的图就是dubbo+spring起来的服务。

**Comment by wu-sheng** [comment]
@ExtremeYu 如果出现任何问题，欢迎把小的demo提供给我们，方便调试。
另外问一下，你们是在什么公司的哪个项目里面使用呢？

**Comment by wu-sheng** [comment]
@ExtremeYu 由于5天没有新的反馈，为了issue列表的直观性，我将暂时关闭此问题，有任何后续的沟通，可以继续在此issue上进行。谢谢。
