### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by TravelEngineers** [wu-sheng/sky-walking#217]
1、agent存在一个bug，当tomcat产生Exception时，agent就会导致内存溢出，从而影响中间件正常使用。
2、agent的配置文件中建议增加扩展名过滤，例如不采集静态资源文件(js/css/jpg等)
2、UI项目组中增加按照OperationName来模糊查询，这样可以提高排障效率。

**Comment by wu-sheng** [comment]
问题一，需要提供一下demo。不确定为什么会发生这个问题。
问题二，参考：https://github.com/wu-sheng/sky-walking/issues/218
问题三，参考https://github.com/wu-sheng/sky-walking/issues/164

**Comment by wu-sheng** [comment]
问题一，参考 https://github.com/wu-sheng/sky-walking/issues/219

**Comment by wu-sheng** [comment]
cc @ascrutae @pengys5

**Comment by wu-sheng** [comment]
问题一（#219）问题三（ #164 ）  已经完成，在3.1中进行发布。

**Comment by TravelEngineers** [comment]
期待着新版本 @wu-sheng

**Comment by wu-sheng** [comment]
3.2 研发版本，已经提供提特性，并提供更高效和稳定的采样机制。
