### ISSUE TITLE
spring cloud 微服务中目前 feign 调用 异常信息 不出现

### ISSUE THREAD

**Issue by hysGitHub** [wu-sheng/sky-walking#263]
您好 目前  我在一个微服务访问另一个 微服务的时候  在 访问者中 添加异常代码  和 关掉 访问服务 异常 无法收集到  希望帮忙看看  测试代码https://pan.baidu.com/s/1nu73g17

**Comment by wu-sheng** [comment]
* 添加异常代码 参考 #262  cc @ascrutae 
* 关掉 访问服务 等待 #261  cc @pengys5 

由于目前3.2版本改造中，有较大优化，所以这个会暂缓一段时间，我们才能完成测试。并同意在3.2中修复。

**Comment by ascrutae** [comment]
已修复在3.2. 

* 添加异常代码 参考PR: #382 
* 关掉 访问服务 参考PR: #376 

关闭issue

**Comment by wu-sheng** [comment]
@hysGitHub 根据你提供的示例，你使用的是Netflix的变种Feign，所以我们之前的库没有支持，已经在3.2中增加了新的插件。感谢反馈。
