### ISSUE TITLE
Problems caused by JRE directory(with space)

### ISSUE THREAD

**Issue by lendo** [wu-sheng/sky-walking#269]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
v3.1

### What version of your OS?
Windows 7

### What version of your JRE?
Oracle JRE 1.8

### What company or project?
My test project

### What did you do?
I installed jre to "C:\Program Files\Java\jdk1.8.0_131". I got this error as below when I startup my collector.
此时不应有 Files\Java\jdk1.8.0_131""。

![tim 20170706173424](https://user-images.githubusercontent.com/82283/27905088-78d039b6-6271-11e7-8468-b5d21e921696.png)

**Comment by wu-sheng** [comment]
@ascrutae Do you provide the collector startup bat file?

**Comment by ascrutae** [comment]
duplicate #250

**Comment by wu-sheng** [comment]
This bug had been fixed, we will release it in v3.2
