### ISSUE TITLE
createAPP大小写错误

### ISSUE THREAD

**Issue by ccknot** [wu-sheng/sky-walking#27]
文件名称：skywalking-webui\src\main\webapp\ftl\app\createAPP.ftl
Controller:
` public String create() {
        return "app/createApp";
    }`

windows下不区分大小写，正常。
linux下异常：

> Could not resolve view with name 'app/createApp' in servlet with name 'springmvc'

**Comment by wu-sheng** [comment]
如下面shell命令，我们的应用已经部署到linux环境下，没有发生所述问题。
请反馈是否由于操作系统等原因，造成这种问题？
```shell
devusr11@host-10-1-241-16:/aifs01/users/devusr11/applications/TD1_TST-S1/skywalking/ftl/app> ls
createAPP.ftl
devusr11@host-10-1-241-16:/aifs01/users/devusr11/applications/TD1_TST-S1/skywalking/ftl/app> uname -a
Linux host-10-1-241-16 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
devusr11@host-10-1-241-16:/aifs01/users/devusr11/applications/TD1_TST-S1/skywalking/ftl/app> lsb_release -a 
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.5 (Final)
Release:	6.5
Codename:	Final
```

**Comment by ccknot** [comment]
Debain 7
不是系统问题，
skywalking-webui\src\main\java\com\ai\cloud\controller\AppMaintainCtl.java
这个文件的return "app/createApp" ，createApp的pp是小写
skywalking-webui\src\main\webapp\ftl\app\createAPP.ftl
这个PP是大写

linux都是区分大小写的吧

**Comment by wu-sheng** [comment]
好的，我已经修改createAPP.ftl文件名，代码已经提交。
不清楚为什么我们的linux系统为什么没有发生问题。
