### ISSUE TITLE
the logs folder was created in the wrong location

### ISSUE THREAD

**Issue by likeflower950** [wu-sheng/sky-walking#278]
### skywalking collector v3.0

my skywalking-collector was installed the path : 
/estrace/skywalking/skywalking-collector
when I started collector at directory 'bin' , 
./startup.sh
the Logs folder was created right location, at the bin same level, two logs files was created 
collector.log
skywalking-server-log4j2.log

but when I started collector at other directory 
example : 
./bin/startup.sh
two logs folders was be created , path : 
/estrace/skywalking/skywalking-collector/logs
and
/estrace/skywalking/logs

The reason of the error:
log4j2.xml
```
<Property name="log-path">../logs</Property>
```
The "log-path" is not relative log4j2.xml, but relative the start direcotry.

##
## 中文解释
如果我在 bin 目录下通过 ./startup.sh 启动 collector 服务，则在bin 同级目录下创建一个logs文件夹，里面包含了 
collector.log
skywalking-server-log4j2.log
两个日志文件，
如果我不在 bin 目录下启动，例如，
在bin 同级目录下通过 ./bin/startup.sh 启动collector 服务，则在bin同级目录下创建一个logs文件夹，里面仅仅包含了
collector.log
同时在bin的上一级目录下也创建了一个 logs文件夹，包含了日志文件：
skywalking-server-log4j2.log

这应该是一种错误配置导致的
在log4j2.xml配置文件中
```
<Property name="log-path">../logs</Property>
```
，为什么得到的结果是相对于当前启动的位置创建的目录，而不是相对于log4j2.xml的位置创建目录！

**Comment by wu-sheng** [comment]
@ascrutae I think this is a bug of startup shell.
