### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by zuochangan** [wu-sheng/sky-walking#304]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?

3.1

### What version of your OS?

mac

### What version of your JRE?

JDK8

### What company or project?

51

### What did you do?

execute mvn -U package -DskipTests  and you will get an error like “Could not resolve dependencies for project org.skywalking:apm-resin-4.x-plugin:jar:3.1-2017: Could not find artifact com.caucho:resin:jar:3.0.26 ”

**Comment by wu-sheng** [comment]
You should follow what ci did : https://github.com/wu-sheng/sky-walking/blob/master/.travis.yml

run `mvn install ***` first.
