### ISSUE TITLE
Question about REST API Document

### ISSUE THREAD

**Issue by swift1911** [wu-sheng/sky-walking#315]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.1

### What version of your OS?
centos 6.7

### What version of your JRE?
1.8.0_131

### What company or project?
collector

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

https://github.com/wu-sheng/sky-walking/wiki/3.0-Collector-TraceSegment-in-JSON-format

哪些字段是必填字段，不能靠一个个猜吧……

**Comment by swift1911** [comment]
数据已经拼接好了，但是不知道哪些是必填字段，服务并没有开始索引

**Comment by wu-sheng** [comment]
这个结构中间是有一个逻辑关系的，可以参考这篇文章的描述：https://github.com/wu-sheng/sky-walking/wiki/3.0-Trace-a-distributed-services-chain 。这篇文章针对A调用B，做了详细的举例。

主要关注以下几个地方：
* A调用B服务，B中的TraceSegmentRef标识的是A中客户端span的值，applicationCode为A的，peer是从A发起对B调用时，使用的ip+port
* SpanId和parentSpanId间的关系需要正确
* A调用B服务，A的客户端需要设置`span.kind: client`, B端的入口Span需要设置`span.kind: server`

**Comment by swift1911** [comment]
我现在的逻辑中，TraceSegmentRef中只能拿到traceSegmentId和spanId，applicationCode和peer必须要有么

**Comment by wu-sheng** [comment]
是的

* applicationCode就是你在首页的拓扑页面看到的每个点下面的字，都是可以自定义的
* peer是客户端调用服务端时的IP+端口，也是用来构建拓扑的。

这两个应该在RPC的时候都能获取到的。否则无法高效、流式的生成拓扑。

**Comment by swift1911** [comment]
好的
    现在client端的实现逻辑是一次上传完整的数据么
    还是上传多次，backend会自动拼接？

**Comment by swift1911** [comment]
描述的更清楚点，就是backend会对traceSegmentId一样的object做merge操作么

**Comment by wu-sheng** [comment]
Segment间关系主要要求：
## ASegment -> BSegment
1. A的segment和B的segment，id不同，globalTraceId相同
1. A中作为客户端的SpanId，是B的ref中的parentSpanId
1. A的segmentId是B的ref中的parentSegmentId
1. B的ref中，applicationCode是A的
1. B的ref中，peer是A的客户端span中的peer tag字段的值
1. 各segment，Span根节点，parentId是-1
1. 各segment，如果涉及RPC的span，都需要设置这三个tag：`span.layer`, `span.kind`, `component`
1. segmentId， globalTraceId必须全局唯一

关于上传，你按照A、B的实例分别上传就可以。后端会根据数据关联性建立拓扑。

**Comment by swift1911** [comment]
Client端
{
    "ac":"client",
    "gt":[
        {
            "id":"1c830705-c75e-4f08-97a0-a59e63a2300a"
        }
    ],
    "rs":[
        {
            "si":"6",
            "ph":"10.12.21.122",
            "ts":"1c830705-c75e-4f08-97a0-a59e63a2300a:6",
            "ac":"server"
        }
    ],
    "ss":[
        {
            "ps":-1,
            "on":"search",
            "ts":{
                "component":"dubbo",
                "span.kind":"client",
                "span.layer":"rpc"
            },
            "st":1501656432210,
            "si":0,
            "et":1501656432214
        }
    ],
    "ts":"1c830705-c75e-4f08-97a0-a59e63a2300a",
    "st":1501656432210,
    "et":1501656432214
}

Server端
{
    "ac":"server",
    "gt":[
        {
            "id":"1c830705-c75e-4f08-97a0-a59e63a2300a"
        }
    ],
    "rs":[

    ],
    "ss":[
        {
            "ps":-1,
            "on":"dubbo:SearcherService.search",
            "ts":{
                "component":"dubbo",
                "span.kind":"server",
                "span.layer":"rpc"
            },
            "st":1501656432211,
            "si":"6",
            "et":1501656432213
        }
    ],
    "ts":"1c830705-c75e-4f08-97a0-a59e63a2300a:6",
    "st":"2017-08-02T14:47:12.211+08:00",
    "et":"2017-08-02T14:47:12.213+08:00"
}

**Comment by swift1911** [comment]
Client端：

{"ac":"agent.blend.esf.fdd","gt":[{"id":"34e3fae1-1a60-41c6-9e22-d4e22d0535b8"}],"rs":[{"si":"0","ph":"10.12.21.122","ts":"34e3fae1-1a60-41c6-9e22-d4e22d0535b8:0","ac":"agent.relation.management.service"}],"ss":[{"ps":-1,"on":"listUsers","ts":{"component":"dubbo","span.kind":"client","span.layer":"rpc"},"st":1501656776951,"si":0,"et":1501656777026}],"ts":"34e3fae1-1a60-41c6-9e22-d4e22d0535b8","st":1501656776951,"et":1501656777026}

server端：
{"ac":"agent.relation.management.service","gt":[{"id":"34e3fae1-1a60-41c6-9e22-d4e22d0535b8"}],"rs":[],"ss":[{"ps":-1,"on":"dubbo:UserService.listUsers","ts":{"component":"dubbo","span.kind":"server","span.layer":"rpc"},"st":1501656776952,"si":"0","et":1501656777025}],"ts":"34e3fae1-1a60-41c6-9e22-d4e22d0535b8:0","st":1501656776952,"et":1501656777025}

这样的数据还是不对吗……

**Comment by swift1911** [comment]
我换了个思路，用spark来对接，这样就跟语言无关了

**Comment by wu-sheng** [comment]
```json
{
    "ac": "agent.blend.esf.fdd",
    "gt": [
        {
            "id": "34e3fae1-1a60-41c6-9e22-d4e22d0535b8"
        }
    ],
    "rs": [
        {
            "si": "0",
            "ph": "10.12.21.122",
            "ts": "34e3fae1-1a60-41c6-9e22-d4e22d0535b8:0",
            "ac": "agent.relation.management.service"
        }
    ],
    "ss": [
        {
            "ps": -1,
            "on": "listUsers",
            "ts": {
                "component": "dubbo",
                "span.kind": "client",
                "span.layer": "rpc"
            },
            "st": 1501656776951,
            "si": 0,
            "et": 1501656777026
        }
    ],
    "ts": "34e3fae1-1a60-41c6-9e22-d4e22d0535b8",
    "st": 1501656776951,
    "et": 1501656777026
}
```
Client端的span中没有peer，这是生成拓扑的关键字段。

```json
{
    "ac": "agent.relation.management.service",
    "gt": [
        {
            "id": "34e3fae1-1a60-41c6-9e22-d4e22d0535b8"
        }
    ],
    "rs": [],
    "ss": [
        {
            "ps": -1,
            "on": "dubbo:UserService.listUsers",
            "ts": {
                "component": "dubbo",
                "span.kind": "server",
                "span.layer": "rpc"
            },
            "st": 1501656776952,
            "si": "0",
            "et": 1501656777025
        }
    ],
    "ts": "34e3fae1-1a60-41c6-9e22-d4e22d0535b8:0",
    "st": 1501656776952,
    "et": 1501656777025
}
```
Server端的rs即refs没有值。即没有表示是server端的数据来自于对应的client端。

这两个segment无法流式的构建拓扑图，是不满足后端分析程序的要求的。

**Comment by swift1911** [comment]
Client端的Rs也是要有值的么……

**Comment by wu-sheng** [comment]
> Client端的Rs也是要有值的么

调用链的第一个节点的segment中可以没有refs。

**Comment by swift1911** [comment]
`{
    "ac": "agent.blend.esf.fdd",
    "gt": [
        {
            "id": "58c45eee-e0e5-4e2a-a39b-efe7c97e65e1"
        }
    ],
    "rs": [
        {
            "si": 0,
            "ph": "10.12.21.122",
            "ts": "58c45eee-e0e5-4e2a-a39b-efe7c97e65e1:0",
            "ac": "agent.relation.management.service"
        }
    ],
    "ss": [
        {
            "ps": -1,
            "on": "listUsers",
            "ts": {
                "peer.host": "10.12.21.117",
                "component": "dubbo",
                "span.kind": "client",
                "span.layer": "rpc"
            },
            "st": 1501658392950,
            "si": 0,
            "et": 1501658393099
        }
    ],
    "ts": "58c45eee-e0e5-4e2a-a39b-efe7c97e65e1",
    "st": 1501658392950,
    "et": 1501658393099
}`


`{
    "ac": "agent.relation.management.service",
    "gt": [
        {
            "id": "58c45eee-e0e5-4e2a-a39b-efe7c97e65e1"
        }
    ],
    "rs": [
        {
            "si": -1,
            "ph": "10.12.21.117",
            "ts": "58c45eee-e0e5-4e2a-a39b-efe7c97e65e1",
            "ac": "agent.blend.esf.fdd"
        }
    ],
    "ss": [
        {
            "ps": -1,
            "on": "dubbo:UserService.listUsers",
            "ts": {
                "peer.host": "10.12.21.122",
                "component": "dubbo",
                "span.kind": "server",
                "span.layer": "rpc"
            },
            "st": 1501658392950,
            "si": "0",
            "et": 1501658393098
        }
    ],
    "ts": "58c45eee-e0e5-4e2a-a39b-efe7c97e65e1:0",
    "st": 1501658392950,
    "et": 1501658393098
}`

不是很清楚client的rs的作用是什么……

**Comment by swift1911** [comment]
可以提供一个client端有rs的示例吗……

**Comment by wu-sheng** [comment]
https://github.com/wu-sheng/sky-walking/wiki/3.0-Trace-a-distributed-services-chain#in-jvm2

**Comment by swift1911** [comment]
上面的数据还有问题么……

**Comment by swift1911** [comment]
![image](https://user-images.githubusercontent.com/9301003/28864171-42184e6c-779e-11e7-9d32-9392799e5925.png)
有个问题，感觉我发什么数据返回都是success

**Comment by wu-sheng** [comment]
服务端si为什么是-1呢？这个应该会影响链路展现。

关于为什么返回成功是因为探针不需要知道的服务端执行情况。额外的开销是没有必要的。

**Comment by wu-sheng** [comment]
其他字段我没有发现问题。是现在还出不来页面么？

**Comment by swift1911** [comment]
是的……还是出不来页面？要不你自己用这个数据跑一下？

**Comment by swift1911** [comment]
再贴一段改过si的数据

`{"ac":"agent.blend.esf.fdd","gt":[{"id":"3d4713e7-ae0c-4ea8-9382-1a5afb0ded6d"}],"rs":[{"si":0,"ph":"10.12.21.122","ts":"3d4713e7-ae0c-4ea8-9382-1a5afb0ded6d:0","ac":"agent.relation.management.service"}],"ss":[{"ps":-1,"on":"listUsers","ts":{"url":"10.12.21.117/listUsers","peer.host":"10.12.21.117","component":"dubbo","span.kind":"client","span.layer":"rpc"},"st":1501669517038,"si":0,"et":1501669517113}],"ts":"3d4713e7-ae0c-4ea8-9382-1a5afb0ded6d","st":1501669517038,"et":1501669517113}`


`{"ac":"agent.relation.management.service","gt":[{"id":"3d4713e7-ae0c-4ea8-9382-1a5afb0ded6d"}],"rs":[{"si":0,"ph":"10.12.21.117","ts":"3d4713e7-ae0c-4ea8-9382-1a5afb0ded6d","ac":"agent.blend.esf.fdd"}],"ss":[{"ps":-1,"on":"dubbo:UserService.listUsers","ts":{"url":"10.12.21.122/dubbo:UserService.listUsers","peer.host":"10.12.21.122","component":"dubbo","span.kind":"server","span.layer":"rpc"},"st":1501669517039,"si":0,"et":1501669517112}],"ts":"3d4713e7-ae0c-4ea8-9382-1a5afb0ded6d:0","st":1501669517039,"et":1501669517112}`

**Comment by swift1911** [comment]
依然感觉没有索引……

**Comment by pengys5** [comment]
@swift1911 
1. 两个报文看着是第一个调用第二个，如果第一个是入口那么RS应该是空的，可是里面有RS，难道前面还有应用？
2. 第一个作为调用方，只有一个入口SPAN，没有出口SPAN。理论SPANID=0的节点一定kind=server，id=1的才会是client。
3. 但是就算这样用elasticsearch里面都会保存出数据来，只是对于不对的区别，所以最好检查一下后端的版本号，看看POM文件呢。

**Comment by pengys5** [comment]
@swift1911 
参考一下这些例子，里面有正常的和异常的都有：
https://github.com/wu-sheng/sky-walking/tree/v3.1/apm-collector/apm-collector-worker/src/test/resources/json/segment/post

**Comment by swift1911** [comment]
1.是的，前面还有应用
2.client端的spanid不是从0开始的吗……
3.后端用的是release里面的3.1版本

**Comment by swift1911** [comment]
现在的表象是服务完全没有log……

**Comment by pengys5** [comment]
https://github.com/wu-sheng/sky-walking/blob/v3.1/apm-collector/apm-collector-worker/src/main/java/org/skywalking/apm/collector/worker/segment/SegmentPost.java

反编译一下包里的这个类，看看是不是源码里面的这样的，出过类似的幺蛾子，就是代码不对，发送客户端看永远是成功，服务端完全没动静。
@ascrutae 张鑫同学，你对这个问题应该很有经验滴，快帮他看看，你们微信加一下，确认一下，然后再用这里的正常目录下的例子发送一次，测试一下。
https://github.com/wu-sheng/sky-walking/tree/v3.1/apm-collector/apm-collector-worker/src/test/resources/json/segment/post

**Comment by swift1911** [comment]
我的微信就是swift1911

**Comment by pengys5** [comment]
客户端的SPANID是从0开始，但是这个segment在你这个例子里面他即是客户端，又是服务端，纯粹的客户端，类似CURL这种操作，没有探针，所以也不会有segment数据，只要有segment，那么他就即是客户端又是服务端了。

**Comment by ascrutae** [comment]
@swift1911  已添加

**Comment by wu-sheng** [comment]
@swift1911 是否问题已经解决？

**Comment by swift1911** [comment]
还有个问题请教下，如何表示收发mq这种异步调用链？

**Comment by swift1911** [comment]
@wu-sheng 现在有数据了，但是碰到空指针异常的问题。
我贴下数据吧

394 {"ac":"agent.blend.esf.fdd","gt":["5d8dbdd4-b519-499c-bcb4-30f3fa051a4f"],"rs":[{}],"ss":[{"ps":-1,"si":0,"lo":[],"on":"listUsers","et":1501731468924,"ti":{},"tb":{},"ts":{"url":"10.12.21.117/listUsers","peer.host":"10.12.21.117","component":"dubbo","span.kind":"client","span.layer":"rpc"},"st":1501731468851}],"ts":"5d8dbdd4-b519-499c-bcb4-30f3fa051a4f","st":1501731468851,"et":1501731468924}

543 {"ac":"agent.relation.management.service","gt":["5d8dbdd4-b519-499c-bcb4-30f3fa051a4f"],"rs":[{"si":0,"ph":"10.12.21.117","ts":"5d8dbdd4-b519-499c-bcb4-30f3fa051a4f","ac":"agent.blend.esf.fdd"}],"ss":[{"ps":-1,"si":0,"lo":[],"on":"dubbo:UserService.listUsers","et":1501731468924,"ti":{},"tb":{},"ts":{"url":"10.12.21.122/dubbo:UserService.listUsers","peer.host":"10.12.21.122","component":"dubbo","span.kind":"server","span.layer":"rpc"},"st":1501731468852}],"ts":"5d8dbdd4-b519-499c-bcb4-30f3fa051a4f:0","st":1501731468852,"et":1501731468924}

**Comment by ascrutae** [comment]
@swift1911 数据格式不正确，rs多了`{}`

**Comment by wu-sheng** [comment]
> 还有个问题请教下，如何表示收发mq这种异步调用链？

这个问题需要 @pengys5 确认下在3.1的情况，我不记得后端有没有补充这个逻辑。作为数据，是需要在layer上标明的。一般layer为http，或者rpc，这个时候是mq.

**Comment by pengys5** [comment]
按目前的代码来看，理论上可以支持一对一消费的MQ，不支持批量消费MQ，但是一直没有正经测试过，^_^， 只能是理论上好使，计划3.2版本发布的时候会正经测试一下。

**Comment by swift1911** [comment]
我刚刚试了MQ的数据，发现完全查不出来

**Comment by swift1911** [comment]
![image](https://user-images.githubusercontent.com/9301003/28911746-2847a624-7864-11e7-846a-5a33a5df941b.png)
直接空指针了

报文如下：
{"ac":"bc.esf.fdd","gt":["2970a0a9-362a-4131-8f59-883503a77bf1"],"rs":[{"si":0,"ph":"10.12.21.117","ts":"2970a0a9-362a-4131-8f59-883503a77bf1#2:0","ac":"estate.stats.esf.fdd"}],"ss":[{"ps":-1,"si":2,"lo":[],"on":"amq:s:VirtualTopic.t_bc_business_event","et":1501742850358,"ti":{},"tb":{},"ts":{"url":"10.12.21.117/amq:s:VirtualTopic.t_bc_business_event","peer.host":"10.12.21.117","component":"dubbo","span.kind":"client","span.layer":"rpc"},"st":1501742850219}],"ts":"2970a0a9-362a-4131-8f59-883503a77bf1#2","st":1501742850219,"et":1501742850358}

{"ac":"estate.stats.esf.fdd","gt":["2970a0a9-362a-4131-8f59-883503a77bf1"],"rs":[{"si":2,"ph":"10.12.21.117","ts":"2970a0a9-362a-4131-8f59-883503a77bf1#2","ac":"bc.esf.fdd"}],"ss":[{"ps":2,"si":0,"lo":[],"on":"bc.busniessEvent","et":1501742850355,"ti":{},"tb":{},"ts":{"url":"10.12.21.117/bc.busniessEvent","peer.host":"10.12.21.117","component":"dubbo","span.kind":"server","span.layer":"rpc"},"st":1501742850355}],"ts":"2970a0a9-362a-4131-8f59-883503a77bf1#2:0","st":1501742850355,"et":1501742850355}

关于批量消费MQ，我自己的实现方案是用#这样的特殊符号做分割，分析的时候根据#之前的ts值reduce回来

**Comment by wu-sheng** [comment]
@swift1911 

> "ts":{"url":"10.12.21.117/amq:s:VirtualTopic.t_bc_business_event","peer.host":"10.12.21.117","component":"dubbo","span.kind":"client","span.layer":"rpc"}

这个layer仅仅是RPC，没有看出和MQ的关系呢。

**Comment by swift1911** [comment]
@wu-sheng 
我先把layer写死成rpc了……

**Comment by wu-sheng** [comment]
@swift1911 如果是rpc，后端应该就会当错普通的rpc处理，和你的普通调用一样。如果之前能出来，这里不应该有问题呢。还是说一直显示trace页面都有问题？

**Comment by swift1911** [comment]
@wu-sheng 有些是好的，问题在于我在发MQ的时候把后面的spanid置为0了

**Comment by swift1911** [comment]
会出现spanid比parentid小的情况

**Comment by wu-sheng** [comment]
@swift1911 异步逻辑为什么要操作spanid呢？这个是描述上下级关系的。`layer`字段是用来给你区分是直接依赖还是异步得。

**Comment by wu-sheng** [comment]
> 会出现spanid比parentid小的情况

关键不是大小的问题，是spanId和parentSpanId要存在，并且构成树形关系，不然肯定无法绘图的。

**Comment by wu-sheng** [comment]
@swift1911 此问题已经接近两周没有新的更新，是否还需要后续讨论？
