### ISSUE TITLE
Support retry when IF_POSSIBLE strategy in DataCarrier

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#317]
Right now, **IF_POSSIBLE**  strategy only try once in selected buffer. When using `SimpleRollingPartitioner`, it is possible to save segments into the same buffer in high concurrency. So, adding retry time ( default is 3 ), will increase the chances to avoid discarding segments.

cc @ascrutae @pengys5

**Comment by wu-sheng** [comment]
related to https://github.com/wu-sheng/sky-walking/commit/4fda33b16cce72fa83900a942ac72c32aff26ae1  cc @ascrutae

**Comment by ascrutae** [comment]
Test success,  relate: [test report](https://github.com/sky-walking/agent-integration-test-report/blob/master/master/report-2017-07-28-23-11.md),close it.
