### ISSUE TITLE
@Transactional的bean无法被追踪

### ISSUE THREAD

**Issue by ascrutae** [wu-sheng/sky-walking#33]
目前bean的增强在TracingEnhanceProcessor.postProcessAfterInitialization中。
@Transactional的Bean由于会被Spring的JDKDynamicAOP给代理了，所以传入到TracingEnhanceProcessor类中就只能获取到Proxy对象(如：实际传入名称为com.sun.proxy.$Proxy17)，并非Bean的实际对象，所以导致无法追踪。
但是如果将增强Bean的功能放到postProcessBeforeInitialization方法，会造成类名被修改，可能会造成Dubbo无法合理的识别类名并发布服务。

**Comment by wu-sheng** [comment]
将不再使用原有的插件模式。
