### ISSUE TITLE
Feedback on using sky-walking

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#34]
请各位留下项目名称，在线系统请留下网址。谢谢各位。

**Comment by lonelive** [comment]
亚信电渠

**Comment by wu-sheng** [comment]
|公司|项目|逻辑集群数量/部署数量|
| ------| ----------- |---------|
|亚信科技（中国）有点公司|ITSC报销系统（）内部|2/4|

**Comment by wu-sheng** [comment]
|公司|项目|逻辑集群数量/应用实例数量|
| ------| ----------- |---------|
|[云开信安信息科技有限公司](http://www.eidsp.cn/)|EIDSP核心系统|8/8|

**Comment by GingoBang** [comment]
编译的时候各种失败。。。。

**Comment by wu-sheng** [comment]
@GingoBang 请具体反馈编译问题。请通过wu.sheng@foxmail.com或者新提出BUG反馈问题。
项目目前的状态都是在本地能够顺利编译并运行的代码。

**Comment by vwyuheng** [comment]
GTrace系统，部署规模4台collector，支撑三个线上业务应用，每天日志量大概4g左右

**Comment by newzys88** [comment]
这源代码没有完全开放呀，不能这样吧？

**Comment by wu-sheng** [comment]
Closing. Not a big deal, now.
