### ISSUE TITLE
Skywalking告警邮件应该支持foxmail

### ISSUE THREAD

**Issue by ascrutae** [wu-sheng/sky-walking#37]
Skywalking告警邮件应该支持foxmail

**Comment by wu-sheng** [comment]
system_config表中config_id=1000，mail.account.prefix在程序逻辑中没有发挥正常作用。
mail.account.prefix应被更名为：mail.account.suffix

**Comment by wu-sheng** [comment]
mail.account.prefix和mail.account.suffix字段都不再使用。统一使用mail.sender标识发件人。原有的mail.username作为鉴权用户

**Comment by lvai125** [comment]
请问skywalking怎么配置邮件告警

**Comment by wu-sheng** [comment]
This is very old issue. Please read new document, there is webhook for alarm. You could implement a server to forward alarm to mail.
