### ISSUE TITLE
Tomcat:Send trace segments to collector failure

### ISSUE THREAD

**Issue by fangchongde** [wu-sheng/sky-walking#370]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
v3.1

### What version of your OS?
centos 7.0 64bit

### What version of your JRE?
openjdk 1.8

### What did you do?
1.在tomcat 8中添加agent，基于修改catalina.sh脚本方式。agent.jar放在／目录
2.访问部署在tomcat中的应用出现以下错误：
ERROR 2017-08-23 15:51:02 CollectorClient :  url======http://192.168.1.184:12800/segments
ERROR 2017-08-23 15:51:02 CollectorClient :  result====={"isSuccess":false,"reason":"For input string: \"[{\"ts\":\"Segment.1503474661815.-1304316032.377.26.9\",\"st\":1503474661815,\"et\":1503474661822,\"ss\":[{\"si\":1,\"ps\":0,\"st\":1503474661819,\"et\":1503474661820,\"on\":\"Mysql/JDBI/PreparedStatement/executeUpdate\",\"ts\":{\"db.instance\":\"webim\",\"span.layer\":\"db\",\"db.type\":\"sql\",\"component\":\"Mysql\",\"span.kind\":\"client\",\"db.statement\":\"select\""}
ERROR 2017-08-23 15:51:02 CollectorClient :  Send trace segments to collector failure.
com.a.eye.skywalking.api.client.RESTResponseStatusError: Unexpected service response code: 500
	at com.a.eye.skywalking.api.client.CollectorClient.sendToCollector(CollectorClient.java:100)
	at com.a.eye.skywalking.api.client.CollectorClient.run(CollectorClient.java:63)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wu-sheng** [comment]
请提供服务端日志，这个错误应该由于服务端的一个错误引起。

**Comment by fangchongde** [comment]
[sky.txt](https://github.com/wu-sheng/sky-walking/files/1244631/sky.txt)

**Comment by pengys5** [comment]
@fangchongde 初步估计是"select""这里的问题，sql语句不完整，而且这个位置是两个双引号，对于json来说是致命的，我们再检查一下。

**Comment by pengys5** [comment]
@fangchongde 你这个被监控的系统能给我们个demo工程吗，实在想不出来探针里面抓取sql的时候为什么没拿全，还多了个双引号。

**Comment by wu-sheng** [comment]
@fangchongde 在周末，sw 3.2已经发布，新版本中已经抛弃json作为主要传输格式，改用GRPC，所以觉得这个问题应该已经解决。

我将关闭此问题，如果出现其他BUG，欢迎提交新的issue，谢谢支持skywalking团队。
