### ISSUE TITLE
The design sketch of instance page and health page

### ISSUE THREAD

**Issue by ascrutae** [wu-sheng/sky-walking#371]
* Health page
![wechatimg2446](https://user-images.githubusercontent.com/12436447/29649668-176bbb00-88c8-11e7-8c02-119b4da34856.jpeg)

* Instance page
![wechatimg2603](https://user-images.githubusercontent.com/12436447/29649674-20326aea-88c8-11e7-86a8-5852233deecc.jpeg)

**Comment by wu-sheng** [comment]
@Fine0830 This is for you to preview the new pages in 3.2
