### ISSUE TITLE
怎么去拦截一个接口类呢？

### ISSUE THREAD

**Issue by hawkingfoo** [wu-sheng/sky-walking#375]
拦截Interface，具体怎么做呢？

谢谢

**Comment by wu-sheng** [comment]
拦截一个借口对应的所有实现么？能描述一下应用场景么？

**Comment by hawkingfoo** [comment]
不是所有的实现。

想开发拦截Thrift的插件。

**Comment by hawkingfoo** [comment]
这里报错是什么原因呢？
java.lang.IllegalStateException: Cannot define non-static or non-public field '_$EnhancedClassInstanceContext' for interface type

**Comment by hawkingfoo** [comment]
@wu-sheng

**Comment by wu-sheng** [comment]
一个特定接口的部分实现？有特定规则？因为接口本身是不包含逻辑，是无法直接拦截的，所谓拦截接口，是拦截的此接口实现。

在3.2版本中（即当前的master），官方提供了基于匹配指定接口的所有实现**HierarchyMatch**，可参考：https://github.com/wu-sheng/sky-walking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/skywalking/apm/agent/core/plugin/match/HierarchyMatch.java#L83

如果有更复杂的规则，则需要你参考上述的实现增加新的匹配器。

在3.2之前的版本，是没有提供相关机制的。欢迎提交相关插件的PR。

**Comment by wu-sheng** [comment]
> 这里报错是什么原因呢？
java.lang.IllegalStateException: Cannot define non-static or non-public field '_$EnhancedClassInstanceContext' for interface type

你是在尝试拦截一个真正的接口吧，这样是不正确的，应该通过接口来匹配实现类，可参考上面的回复。

**Comment by hawkingfoo** [comment]
好的，谢谢了~~

**Comment by wu-sheng** [comment]
我将关闭此问题，欢迎积极pr，贡献thift相关插件。谢谢。
