### ISSUE TITLE
一个项目中同时使用mysql和oracle时，其中有一个数据源获取不到连接，报空指针的异常。

### ISSUE THREAD

**Issue by yupd** [wu-sheng/sky-walking#383]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.1

### What version of your OS?
windows7，tomcat7.0.75

### What version of your JRE?
jdk1.8

### What company or project?
通过探针技术获取三层关联信息。

### What did you do?
package est;
import java.sql.Connection;
package est;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class MysqlService {
        public static int exeSql() throws Exception{
	     Class.forName("com.mysql.jdbc.Driver");
	     String url = "jdbc:mysql://localhost:3306/test";
	     String user = "root";
	     String password = "root";
	     Connection conn = DriverManager.getConnection(url, user, password);
	     PreparedStatement ps = conn.prepareStatement("select count(*) as ct from user");
	     ResultSet rs = ps.executeQuery();
	     int cnt = 0;
	     if(rs.next()){
		cnt = rs.getInt("ct");
	     }
	     rs.close();
	    ps.close();
	    conn.close();
	    return cnt;
        }
}

package est;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class OracleService {

public static int exeSql() throws Exception{
	Class.forName("oracle.jdbc.driver.OracleDriver");
	String url = "jdbc:oracle:thin:@localhost:1521:xe";
	String user = "oracle";
	String password = "oracle";
	Connection conn = DriverManager.getConnection(url, user, password);
	PreparedStatement ps = conn.prepareStatement("select count(*) as ct from user");
	ResultSet rs = ps.executeQuery();
	int cnt = 0;
	if(rs.next()){
		cnt = rs.getInt("ct");
	}
	rs.close();
	ps.close();
	conn.close();
	return cnt;
}

}

package est;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class HelloServlet extends HttpServlet {

public void doGet(HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException {

	int cnt1 = 0, cnt2 = 0;
	
	try {
		cnt1 = MysqlService.exeSql();
	} catch (Exception e) {
		e.printStackTrace();
	}
	
	try {
		cnt2 = OracleService.exeSql();
	} catch (Exception e) {
		e.printStackTrace();
	}
        // ------------省略------------

**Comment by yupd** [comment]
[Uploading muti-ds-bug-webdemo.zip…]()

**Comment by yupd** [comment]
`package est;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class MysqlService {

	public static int exeSql() throws Exception{
		Class.forName("com.mysql.jdbc.Driver");
		String url = "jdbc:mysql://localhost:3306/test";
		String user = "root";
		String password = "root";
		Connection conn = DriverManager.getConnection(url, user, password);
		PreparedStatement ps = conn.prepareStatement("select count(*) as ct from user");
		ResultSet rs = ps.executeQuery();
		int cnt = 0;
		if(rs.next()){
			cnt = rs.getInt("ct");
		}
		rs.close();
		ps.close();
		conn.close();
		return cnt;
	}
	
	public static void main(String[] args) throws Exception{
		System.out.println(exeSql());
	}
}
`
`package est;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class OracleService {

	public static int exeSql() throws Exception{
		Class.forName("oracle.jdbc.driver.OracleDriver");
		String url = "jdbc:oracle:thin:@localhost:1521:xe";
		String user = "oracle";
		String password = "oracle";
		Connection conn = DriverManager.getConnection(url, user, password);
		PreparedStatement ps = conn.prepareStatement("select count(*) as ct from user");
		ResultSet rs = ps.executeQuery();
		int cnt = 0;
		if(rs.next()){
			cnt = rs.getInt("ct");
		}
		rs.close();
		ps.close();
		conn.close();
		return cnt;
	}
	
	public static void main(String[] args) throws Exception{
		System.out.println(exeSql());
	}
}
`
`package est;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class HelloServlet extends HttpServlet {

	
	public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		int cnt1 = 0, cnt2 = 0;
		
		try {
			cnt1 = MysqlService.exeSql();
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		try {
			cnt2 = OracleService.exeSql();
		} catch (Exception e) {
			e.printStackTrace();
		}`

**Comment by ascrutae** [comment]
@yupd  非常感谢提出这个issue，这个是skywalking的jdbc插件的一个bug。已经修复在PR: #384
