### ISSUE TITLE
.net 客户端在哪里

### ISSUE THREAD

**Issue by brotherhorse** [wu-sheng/sky-walking#397]
Please answer these questions before submitting your issue.

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

**Comment by wu-sheng** [comment]
目前，没有PMC成员，contributor或者其他社区成员，有意向提供C#版本。不好意思。

**Comment by brotherhorse** [comment]
谢谢答复，目前在测试 大众点评的 Cat

________________________________
发件人: 吴晟 Wu Sheng <notifications@github.com>
发送时间: 2017年9月5日 8:41
收件人: wu-sheng/sky-walking
抄送: brotherhorse; Author
主题: Re: [wu-sheng/sky-walking] .net 客户端在哪里 (#397)


目前，没有PMC成员，contributor或者其他社区成员，有意向提供C#版本。不好意思。

―

**Comment by wu-sheng** [comment]
好的，如果有问题，随时联系。
