### ISSUE TITLE
Tomcat8 agent配置

### ISSUE THREAD

**Issue by jameskypee** [wu-sheng/sky-walking#420]
修改 bin目录下  catalina.bat
在 setlocal后面加入agent配置 
注意写法 一定是set "CATALINA_OPTS=--javaagent:youpath\skywalking-agent.jar"
参考：
set "CATALINA_OPTS=-server -Xms528m -Xmx528m -XX:PermSize=256m -XX:MaxPermSize=358m -javaagent:E:\apache-tomcat-8.5.20\skywalking-agent.jar -DconfigPath=E:\apache-tomcat-8.5.20\sky-walking.config"
linux配置与windows配置大同小异，注意修改文件为catalina.sh及agentjar路径即可

**Comment by wu-sheng** [comment]
I will update this to the WIKI. Thank you.

**Comment by wu-sheng** [comment]
Already provided here: https://github.com/wu-sheng/sky-walking/wiki/3.2-%E9%83%A8%E7%BD%B2%E6%8E%A2%E9%92%88Agent#tomcat%E9%85%8D%E7%BD%AE%E6%8E%A2%E9%92%88faq . This is a 3.2 document, we will release it soon.
