### ISSUE TITLE
Separate the ContextCarrier for supporting tracecontext-spec

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#422]
Try to separate the ContextCarrier into two parts, 1)Major part, for following tracecontext-spec, 2)Extend part, for skywalking itself.

This also depends on #421 

cc @adriancole, Hope this works. :)  Do you have any schedule to post a list about Which tracers are supporting the spec?

**Comment by wu-sheng** [comment]
cc @ascrutae @pengys5 for news updated.

**Comment by wu-sheng** [comment]
Put this into TBD

**Comment by wu-sheng** [comment]
Already support multi headers for propagation.

**Comment by adriancole** [comment]
I don't have plans to make a supported tracers list, but sounds good. maybe @mtwo or @bogdandrutu does?

**Comment by wu-sheng** [comment]
If we can keep the spec stabilize, we can keep the right list. Otherwise, it is too hard. But having that list, we can tell the interop works among those tracers, right? That is the spec for. @mtwo, @bogdandrutu @adriancole

**Comment by mtwo** [comment]
@wu-sheng agreed, we should have a list. I think it makes sense to create during the first (v0.1 I guess) release ... do you agree?

**Comment by wu-sheng** [comment]
@mtwo yes. and skywalking is going to change head format aftet 0.1 released.
