### ISSUE TITLE
Provide Struts2MVC plugin

### ISSUE THREAD

**Issue by sunstear2015** [wu-sheng/sky-walking#436]
weblogic中间容器应用也比较多，能否添加对weblogic的支持

**Comment by wu-sheng** [comment]
@ascrutae 他使用weblogic+struts2，我建议我们支持struts2的插件，然后做一下weblogic
兼容性测试就可以。

**Comment by wu-sheng** [comment]
@sunstear2015 请提供一下weblogic和struts2的版本，利于测试，谢谢。

**Comment by sunstear2015** [comment]
string+structs2+ibatis
(spring 3.0.5 structs2  2.3.34 )
weblogic :12.1.3

**Comment by wu-sheng** [comment]
Provide Struts2 plugin in 3.2.1  I think that will be enough for support tracing

**Comment by LifeFly** [comment]
路过同问  weblogic里面部署了ejb   能支持不？

**Comment by wu-sheng** [comment]
@LifeFly Please submit a new issue for supporting EJB. We manage requirements through issues. So please don't discuss irrelative questions/requirements here. Thanks.

**Comment by wu-sheng** [comment]
> 路过同问 weblogic里面部署了ejb 能支持不？

We can discuss how to support EJB in another issue, please you submit one.

**Comment by ascrutae** [comment]
Ref: #445

**Comment by wu-sheng** [comment]
Merged, closing
