### ISSUE TITLE
「sky-walking 3.2」 collect trace info without operation name.

### ISSUE THREAD

**Issue by aliluyahoho** [wu-sheng/sky-walking#439]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
pre-release:3.2

### What version of your OS?
4.2.0-27-generic #32~14.04.1-Ubuntu

### What version of your JRE?
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

### What company or project?
netease

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

After deployed the latest version of sky-walking, find my project trace info without operation name.
My Controller Code as following:

	@ResponseBody
		@RequestMapping(path = "/gateway/callback", method = RequestMethod.POST,
				produces=MediaType.APPLICATION_JSON_UTF8_VALUE)
		public String gatewayCallback(@RequestParam Map<String, String> paramMap){
			log.info(String.format("standard callback start:[%s]", paramMap.toString()));
	
			...
	
		}

**Comment by wu-sheng** [comment]
@ascrutae This is a confirmed bug.

**Comment by ascrutae** [comment]
This issue has been fix in PR: #458
