### ISSUE TITLE
RemoteCommonServiceGrpc can not find in branch master

### ISSUE THREAD

**Issue by reesechou2014** [wu-sheng/sky-walking#457]
apm-collector/apm-collector-remote/src/main/proto/RemoteCommonService.proto  

this proto file can not find  RemoteCommonServiceGrpc

**Comment by wu-sheng** [comment]
Please post your `mvn package` log. collect-remote and network module depends on grpc protoc util.

**Comment by reesechou2014** [comment]
你好,是这样子的,我用proto的maven插件生成了java类后,并没有找到RemoteCommonServiceGrpc这个类
![image](https://user-images.githubusercontent.com/8568508/30783790-9c44600e-a17b-11e7-9036-8c586ed8c309.png)

![image](https://user-images.githubusercontent.com/8568508/30783825-ffa238d8-a17b-11e7-81af-85bc5fc13915.png)

**Comment by wu-sheng** [comment]
protobuf目录下应该有两个目录，java和grpc，这个类在grpc目录中。`RemoteCommonService.proto`文件中也明确定义了此服务。所以，请检查gRPC和maven环境，以及IDE设置。

另外，根据Travis-ci编译情况，此工程没有编译问题：https://travis-ci.org/wu-sheng/sky-walking

<img width="488" alt="wx20170924-230216 2x" src="https://user-images.githubusercontent.com/5441976/30783853-72c3f57c-a17c-11e7-9255-83686f8365a2.png">

**Comment by reesechou2014** [comment]
好的,我试试,3q

**Comment by cdoewew** [comment]
> 好的,我试试,3q

大佬，搞好了没有？
