### ISSUE TITLE
How many plugins in skywalking-agent,what can i do for disable it?

### ISSUE THREAD

**Issue by zhangkewei** [wu-sheng/sky-walking#479]
This is I find out:
dubbo, httpclient-4.x, jdbc, jedis-2.x, jetty-client-9.x, jetty-server-9.x, mongodb-3.x, motan-0.x, nutz-http-1.x, nutz-mvc-annotation-1.x, spring-cloud-feign-1.x, spring-concurrent-util-4.x, spring-mvc-annotation-4.x, spring-resttemplate-4.x, struts2-2.x, tomcat-7.x/8.x, toolkit-log4j2, toolkit-logback, toolkit-opentracing, toolkit-trace.

**Comment by wu-sheng** [comment]
Provide docs for this.
Eng: https://github.com/wu-sheng/sky-walking/wiki/3.2.2-Plugin-list-and-how-to-disable-plugin
zh: https://github.com/wu-sheng/sky-walking/wiki/3.2.2-Plugin-list-and-how-to-disable-plugin-zh
