### ISSUE TITLE
 Could not find or load main class com.ai.cloud.skywalking.reciever.CollectionServer

### ISSUE THREAD

**Issue by NikoTung** [wu-sheng/sky-walking#56]
在单台机器上部署时启动报了这个错。

    ~/installer/bin# Error: Could not find or load main class    com.ai.cloud.skywalking.reciever.CollectionServer

log 如下

    CLASSPATH=./../lib/zookeeper.jar:./../lib/xz.jar:./../lib/xmlenc.jar:./../lib/stax-api.jar:./../lib/snappy-java.jar:./../lib/slf4j-log4j12.jar:./../lib/slf4j-api.jar:./../lib/skywalking-server-1.0-Final.jar:./../lib/skywalking-protocol.jar:./../lib/protobuf-java.jar:./../lib/paranamer.jar:./../lib/netty.jar:./../lib/netty-all.jar:./../lib/log4j.jar:./../lib/log4j-core.jar:./../lib/log4j-api.jar:./../lib/junit.jar:./../lib/jsr305.jar:./../lib/jsch.jar:./../lib/joni.jar:./../lib/jetty-util.jar:./../lib/jedis.jar:./../lib/jdk.tools.jar:./../lib/jcodings.jar:./../lib/jaxb-api.jar:./../lib/jackson-mapper-asl.jar:./../lib/jackson-core-asl.jar:./../lib/httpcore.jar:./../lib/httpclient.jar:./../lib/htrace-core.jar:./../lib/hbase-protocol.jar:./../lib/hbase-common.jar:./../lib/hbase-client.jar:./../lib/hbase-annotations.jar:./../lib/hamcrest-core.jar:./../lib/hadoop-yarn-common.jar:./../lib/hadoop-yarn-api.jar:./../lib/hadoop-mapreduce-client-core.jar:./../lib/hadoop-common.jar:./../lib/hadoop-auth.jar:./../lib/hadoop-annotations.jar:./../lib/guava.jar:./../lib/gson.jar:./../lib/findbugs-annotations.jar:./../lib/commons-pool2.jar:./../lib/commons-net.jar:./../lib/commons-math3.jar:./../lib/commons-logging.jar:./../lib/commons-lang.jar:./../lib/commons-io.jar:./../lib/commons-httpclient.jar:./../lib/commons-el.jar:./../lib/commons-digester.jar:./../lib/commons-configuration.jar:./../lib/commons-compress.jar:./../lib/commons-collections.jar:./../lib/commons-codec.jar:./../lib/commons-cli.jar:./../lib/commons-beanutils.jar:./../lib/commons-beanutils-core.jar:./../lib/avro.jar:./../lib/api-util.jar:./../lib/api-asn1-api.jar:./../lib/apacheds-kerberos-codec.jar:./../lib/apacheds-i18n.jar:./../lib/activation.jar:./../config:

**Comment by wu-sheng** [comment]
此原因由于启动脚本错误造成
应修改启动脚本swserver.sh脚本最后一行：
```shell
$JAVA ${JAVA_OPTS} -classpath $CLASSPATH com.a.eye.skywalking.reciever.CollectionServer >> ${SW_SERVER_BIN_DIR}/../log/sw-server.log & 2>&1&
```
可以参考新的release: v1.0 Final hotfix1
