### ISSUE TITLE
Use ElasticSearch in stead of HyperSql as Index storage. Please submit report of ElasticSearch performance report.

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#57]
* Performance Report of ElasticSearch

**Comment by ascrutae** [comment]
* **Environment** : CPU 2.2 GHz Intel Core i7,  16G, SSD


**1 Thread**

|Thread Count | Data Count | cost|
|---|---|---|
|1| 100W| 18'|
|1| 200W| 36'|
|4| 100W| 18'|
|4|200W | 33'|
|8| 100W| 19'|
|8| 200W| 32'|
|8| 400W| 62'|

**Comment by wu-sheng** [comment]
Conclusion: less than 400W data, linear cost growth with data growing.

**Comment by wu-sheng** [comment]
### 1st DAY Volume / Fatigue  TEST REPORT
* added 70 million spans in 3 hours, cost 12G disk space ( index file only )
* **Speculate:**
    * Process 6400tps incoming spans
    * 45 billion spans cost 7T disk space ( not included data file )

_Waiting for further report..._

**Comment by wu-sheng** [comment]
@zhxiaogg **TEST REPORT** for storage node, keep you in the loop.

**Comment by wu-sheng** [comment]
Continue with **node performance test**, https://github.com/wu-sheng/sky-walking/issues/64
