### ISSUE TITLE
To all skywalking-developer

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#58]
### Welcome everyone from [skywalking-developer org](https://github.com/skywalking-developer)

Please observe the following rules:
* All Issues and Features will be managed this **Issues Page**.
* All Issues ( features or bugs ) descriptions should be in English.
* If Everyone want to develop on any feature, you should comment on the Issue, and set a deadline for yourself.
* You should create a branch on **skywalking-developer/sky-walking**, named as  `features/issueId`, such as `features/11` (link to Issues 11 on this **Issues Page** )
* When finish your feature,  you send a **pull request** to **wu-sheng/sky-walking**, and we can discuss the detail (design, mechanism, performance, etc.). When everything is look good to the whole team, I will merge the feature. And, Wo-ah, you will begin an official contributor of **sky-walking**

**Comment by wu-sheng** [comment]
To all new members: @zhxiaogg , @SingleX , @zhang2014

**Comment by wu-sheng** [comment]
@zhxiaogg , I will **@** you on the issue, which your team should focus ( some issues are _Irrelevant_).

As a owner of skywalking-developer org, you can manage the org and repos. Please remember to sync `https://github.com/skywalking-developer/sky-walking`'s master to `https://github.com/wu-sheng/sky-walking`'s master ( In order to make sure, PR will be auto merged). 

There is a way to set **auto-sync**, you can search it online, and test it.

**Comment by zhxiaogg** [comment]
Looks great! 

@wu-sheng thanks for your detail guides, that's very kind!

**Comment by ascrutae** [comment]
OK

**Comment by SingleX** [comment]
OK

**Comment by wu-sheng** [comment]
For further notice, all issue will be tagged ** Feature4OrgDeveloper**

**Comment by zhx19940113** [comment]
OK
