### ISSUE TITLE
New trace UI

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#60]
- [ ] proto page should like the image below.
- [ ] use **JSON** as a input. JSON contains a tree data structure which can define parent-child relation, every node on it has duration.

* json should like this, could add as many childs as your want.
```json
{
    "operationName": "/uri/transaction/serviceA",
    "startTime": 0,
    "duration": 1000,
    "childs": [
        {
            "operationName": "FunctionA",
            "startTime": 100,
            "duration": 700,
            "childs": []
        },
        {
            "operationName": "FunctionB",
            "startTime": 9500,
            "duration": 50,
            "childs": []
        }
    ]
}
```

![wechatimg298](https://cloud.githubusercontent.com/assets/5441976/20382622/a001e196-ace7-11e6-9365-f2f4f0f8091f.jpeg)

@TastySummer

**Comment by wu-sheng** [comment]
@TastySummer  , this is a new json format:

```json
[
  {
    "operationName": "client transaction from start to end",
    "startTime": 0,
    "duration": 1000,
    "levelId": "0",
    "parentLevelId": "-1"
  },
  {
    "operationName": "load balancer transaction from start to end",
    "startTime": 50,
    "duration": 900,
    "levelId": "0.0",
    "parentLevelId": "0"
  },
  {
    "operationName": "auth",
    "startTime": 60,
    "duration": 50,
    "levelId": "0.0.0",
    "parentLevelId": "0.0"
  },
  {
    "operationName": "billing",
    "startTime": 110,
    "duration": 50,
    "levelId": "0.0.1",
    "parentLevelId": "0.0"
  },
  {
    "operationName": "resource allocation and provisioning",
    "startTime": 160,
    "duration": 700,
    "levelId": "0.0.2",
    "parentLevelId": "0.0"
  },
  {
    "operationName": "container start up",
    "startTime": 400,
    "duration": 350,
    "levelId": "0.0.2.0",
    "parentLevelId": "0.0.2"
  },
  {
    "operationName": "storage allocation",
    "startTime": 410,
    "duration": 200,
    "levelId": "0.0.2.0.0",
    "parentLevelId": "0.0.2.0"
  },
  {
    "operationName": "start-up scripts",
    "startTime": 610,
    "duration": 20,
    "levelId": "0.0.2.1",
    "parentLevelId": "0.0.2"
  }
]
```

* levelId is the node identifier ( unique ) in the graph
* parentLevelId is parent node id of this node. should have a vertical line, link to the parent node
* the sequence of the json array, is the flow sequence of the graph

**Comment by TastySummer** [comment]
第二种格式可以 @wu-sheng

**Comment by wu-sheng** [comment]
```
[
  {
    "operationName": "client transaction from start to end",
    "startTime": 0,
    "duration": 1000,
    "levelId": "0",
    "parentLevelId": "-1"
  },
  {
    "operationName": "load balancer transaction from start to end",
    "startTime": 50,
    "duration": 900,
    "levelId": "0.0",
    "parentLevelId": "0"
  }
  ...
]
```

@ascrutae , use the second format json ^^^ in ui page.

**Comment by ascrutae** [comment]
👌

**Comment by TastySummer** [comment]
因为点击各节点会弹出模态框，所以json数据格式稍微有点变动
![image](https://cloud.githubusercontent.com/assets/13374074/20882953/7f6f025c-bb1e-11e6-866c-0add7237b290.png)
业务字段部分为一行，不要换行，如果需要换行用“\n”表示。

**Comment by TastySummer** [comment]
![image](https://cloud.githubusercontent.com/assets/13374074/20883032/f127add6-bb1e-11e6-82ab-70b605877301.png)
 模态框雏形

**Comment by wu-sheng** [comment]
This whole UI will be provided in version 2.1-2017. On the next iteration.

**Comment by wu-sheng** [comment]
Closing

**Comment by wu-sheng** [comment]
As 3.0 comes, this new UI is back. Here are the color resources.

![chart_](https://cloud.githubusercontent.com/assets/5441976/24443054/a4d1d46a-1493-11e7-9a1f-cef68989fe77.png)
![chart-](https://cloud.githubusercontent.com/assets/5441976/24443056/a66c75dc-1493-11e7-8eb2-fef4a80d2aba.png)

**Comment by wu-sheng** [comment]
The UI has moved to sky-walking-ui. The issue stays because it existed long time ago.

**Comment by pengys5** [comment]
see mater
