### ISSUE TITLE
Join OpenTracing

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#72]
Create application-toolkit-opentracing, or support https://github.com/opentracing-contrib by using sky-walking plugin mechanism, if https://github.com/opentracing-contrib/java-globaltracer/pull/1 is finished, and released.

**Comment by wu-sheng** [comment]
Add a new application toolkit: skywalking-toolkit-opentracing

**Comment by wu-sheng** [comment]
![wechatimg2](https://cloud.githubusercontent.com/assets/5441976/22696502/29aa37ae-ed89-11e6-8f6f-c0dd96b13977.jpeg)

New demo trace tree. @rayzhang0603 , I think you will be interested in opentracing-motan trace tree node. 😁

**Comment by wu-sheng** [comment]
@bensigelman, this is my trace tree visualization with motan-opentracing node. 

motan-opentracing filter uses spi to find tracer implementation.

**Comment by bensigelman** [comment]
@wu-sheng nice! thanks for `@bensigelman`ing me.
