### ISSUE TITLE
support trace Hprose-java

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#73]
[Hprose](https://github.com/andot/hprose) (High Performance Remote Object Service Engine）,  support multi-platforms, sky-walking choose to support its java-edition.

@andot

**Comment by andot** [comment]
@wu-sheng How should I do?

**Comment by wu-sheng** [comment]
I think it should be **Nothing**  to change. We will use dynamic class source change tech to inject a filter. Maybe later, I need your help to confirm which framework's class and method should be intercepted.

**Comment by andot** [comment]
Thank you!

**Comment by wu-sheng** [comment]
Use optracing toolkit activation to support this rpc framework.

**Comment by wu-sheng** [comment]
@andot , I think hprose-java opentracing will be supported automaticly, by skywalking-opentracing-toolkit. 

See https://github.com/wu-sheng/sky-walking/issues/72

**Comment by wu-sheng** [comment]
I will close this issue, be ready for 2.1-release. If anything goes right, we can reopen this.
