### ISSUE TITLE
%x of log4j toolkit may have conflict with the log4j NDC

### ISSUE THREAD

**Issue by theopengroup** [wu-sheng/sky-walking#77]
is it better to choose another char?

**Comment by wu-sheng** [comment]
Can you describe the conflict, we have aware of the `%x`'s confliction. But I want to make sure what happen on your side.

When we use `%x` on testing, no error occurs. Does this trigger NDC not working?

**Comment by theopengroup** [comment]
Sorry, I just read codes without testing. I think the NDC may not be printed in this case.

**Comment by wu-sheng** [comment]
Fixed in next version. Seem you are right.
