### ISSUE TITLE
[Big Change] Update the trace-structure

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#83]
The origin trace-structure is like a tree-struction, every span has no more than on one span. Right now,  this seems not right, all the time. 

When we face to some scenarios, like batch consume from MQ (e.g. https://github.com/wu-sheng/sky-walking/issues/51), we need more than one parent span. More likely, these should existed multi-parent traceid and spanid.

This is also confirmed by OpenTracing spec, which a trace is definitely a DAG, rather than a tree.

So this will the biggest change, since release 2.x

If we decide to do this, we will update sky-walking to 3.x.

btw @ascrutae , @pengys5

**Comment by wu-sheng** [comment]
The whole new structure of **Distributed Trace**:

```
Traces-DAG ( Logic, across-proceas, across-thread )

  Trace ( in thread )
      traceId ( Global Unique Id or Random.long )
      startTime
      endTime
      PrimaryParentTraceRef
      ParentTracieRefs ( list : support batch process )
          ParentTraceId
          ParentSpanId

      Span ( list )
           SpanId
           ParentSpanId
           OperationName
           startTime
           endTime
           Tags
           Log(error, event, stack)
```

**Comment by wu-sheng** [comment]
There will be two ways to store **Logic distributed trace**. For the notice, `request/ack span` things did NOT bring any clear advantage, so I will be deprecated.

We will go to traditional trace/span thing. But we have three options here.
1. Store a `in-thread` trace object, after it finished (`in-thread`), including all spans in it.
1. Store separated span objects, after the trace finished.
1. Store separated span objects, like ^^^ one, but not until the trace finished, just after the span finished.

These three ways don't have much differences, if we store spans in an Elastic Search Cluster, which I think it's the best choice for now. But we still need a decision, so I think here need a vote.

In Elastic Search Cluster, it is very easy to deploy, easy to index(traceid/spanid/parent-stuffs/tags/logs), easy to search(same as index).

**Comment by wu-sheng** [comment]
Maybe, if we want to follow OpenTracing spec more, I can make this concept changes:
- Traces-DAG -> Trace
- Trace -> SubTrace

**Comment by wu-sheng** [comment]
> Store a in-thread trace object, after it finished (in-thread), including all spans in it.

+1, javaagent -> server node, the analysis is based on `TraceSegment`, it will be easier to find **root causes**. (e.g. slow sql, slow rpc, high frequency db access, etc.)

**Comment by wu-sheng** [comment]
Dev on [branch feature/3.0](https://github.com/wu-sheng/sky-walking/tree/feature/3.0)

**Comment by ascrutae** [comment]
> Store separated span objects, like ^^^ one, but not until the trace finished, just after the span finished

+1, The amount of data sent to the storage node can be controlled, and this solution can solve  the agent will take up a lot of memory  in the case of the large number of synchronous calls

**Comment by wu-sheng** [comment]
@ascrutae  I Saw your point. But how to process the `find causes`? You need to cache on server side, and, clearly, it costs the same memory. Also skywalking will face tons of phycical

**Comment by wu-sheng** [comment]
Sorry

**Comment by ascrutae** [comment]
I just mean the span data generated during the execution of the trace will be stored in memory and the data will be sent out until the trace is complete. If the trace is high and the application contains a large number of such trace, it will have an effect on the application memory

**Comment by wu-sheng** [comment]
The new `TraceSegment` Object has been released. You can preview it:

https://github.com/wu-sheng/sky-walking/blob/feature/3.0/skywalking-commons/skywalking-trace/src/main/java/com/a/eye/skywalking/trace/TraceSegment.java

**Comment by wu-sheng** [comment]
@ascrutae , still, you don't consider of the analysis scenario, how to do that, and how to do that easily. This is a major point of version 3.0

**Comment by bensigelman** [comment]
@wu-sheng it's a little scary to actually implement full DAG support from a visualization standpoint... certainly can be done (see X-Trace from Berkeley, etc), but lots of corner cases.

I like the idea of modeling a "trace" as a DAG of sub-trees (where each tree is, well, a *tree*: a single-parent-only DAG). Then you can visualize every tree in straightforward tree-like ways and only handle the complicated multi-parent cases between trees. Not sure if this makes sense, I realize I'm leaving out a lot of detail.

**Comment by wu-sheng** [comment]
@ascrutae , I have the same concern as you are. So, in here, I just change the data-structure, and you can see it is a DAG model. 

In visualization, I prepare to just show the trace-tree by traceSegementId and PrimaryParentTraceRef. It is still a Tree, rather than a real DAG (single-parent-only, as your mentioned). And for `ParentTracieRefs`, I want to give only some links in UI. If the users click it, they will see the detail of sub-tree.

**Comment by wu-sheng** [comment]
The major data structures of trace are in these packages:
- https://github.com/wu-sheng/sky-walking/tree/feature/3.0/skywalking-commons/skywalking-trace/src/main/java/com/a/eye/skywalking/trace
- https://github.com/wu-sheng/sky-walking/tree/feature/3.0/skywalking-sniffer/skywalking-api/src/main/java/com/a/eye/skywalking/context

**Comment by wu-sheng** [comment]
As 3.0 is nearly ready to release, closing this..
