### ISSUE TITLE
TraceId这个类放哪里去了

### ISSUE THREAD

**Issue by NicholasQu** [wu-sheng/sky-walking#88]
源码中的TraceId类找不到，还有其他同包内的类，方便请上传。

**Comment by ascrutae** [comment]
什么版本的代码？

**Comment by wu-sheng** [comment]
请参考在线ci打包脚本，确保此步骤被执行。
https://github.com/wu-sheng/sky-walking/blob/master/.travis.yml#L12-L13

**Comment by NicholasQu** [comment]
谢谢楼上各位， 已搞定。另外补充一下，让其他人少走弯路。

1. 在运行clean install时， 可能会报错 javax.jms.1.1.jar 不存在（到sun官网上是下载不到的），最好提前将这个jar下载到自己的本地库。
http://mvnrepository.com/artifact/javax.jms/jms/1.1

2. 加上 -DskipTests， 否则会有测试用例报错。

Done.

**Comment by wu-sheng** [comment]
@NicholasQu 

> 在运行clean install时， 可能会报错 javax.jms.1.1.jar 不存在（到sun官网上是下载不到的），最好提前将这个jar下载到自己的本地库。
http://mvnrepository.com/artifact/javax.jms/jms/1.1

你贴出的是maven中央仓库地址，如果本地没有网络问题，应该是可以自动编译的。在线编译日志可参考：https://travis-ci.org/wu-sheng/sky-walking/

>加上 -DskipTests， 否则会有测试用例报错。

能反馈是在哪里测试不能通过呢？windows平台？因为我们的travis-ci在linux环境上显示是正常的。

**Comment by NicholasQu** [comment]
问题1： 不管我本地还是内网的nexus私服， 访问外部网络都不会有问题，报错信息是到sun的一个地址下载jms的jar, 那个路径是不可能下载的到的。 这个因人而异吧， 只是个建议。

问题2：至于junit, 确实是windows平台开发， 刚才-X看了一下， 是 
**ElasticBootstrapTest**
org.junit.ComparisonFailure: Elastic Home : expected:<....\skywalking-storage[\data\]index> but was:<....\skywalking-storage[/data/]index>

**ElasticConfigModifierTest**
java.nio.file.FileSystemException: D:\0.Dev\3.Repository\Github\NicholasQu\sky-walking\skywalking-storage-center\skywalking-storage\target\test-classes\test\config\elasticsearch.yml: 另一个程序正在使用此文件，进程无法访问。

请考虑兼容下。

**Comment by wu-sheng** [comment]
@NicholasQu , Good to know, Thanks.
